import lombok.*;

import java.sql.Timestamp;
@AllArgsConstructor
@NoArgsConstructor(access = AccessLevel.PUBLIC)
@Builder
@Data
public class User {

    private int id;
    private String name;
    private String comment;
    private double number1;
    private double number2;
    private Timestamp createdDate;

    private String c1;
    private String c2;
    private String c3;
    private String c4;
    private String c5;
    private String c6;
    private String c7;
    private String c8;
    private String c9;
    private String c10;
    private String c11;
    private String c12;
    private String c13;
    private String c14;
    private String c15;
    private String c16;
    private String c17;
    private String c18;
    private String c19;
    private String c20;
    private String c21;
    private String c22;
    private String c23;
    private String c24;
    private String c25;
    private String c26;
    private String c27;
    private String c28;
    private String c29;
    private String c30;
    private String c31;
    private String c32;
    private String c33;
    private String c34;
    private String c35;
    private String c36;
    private String c37;
    private String c38;
    private String c39;
    private String c40;
    private String c41;
    private String c42;
    private String c43;
    private String c44;
    private String c45;
    private String c46;
    private String c47;
    private String c48;
    private String c49;
    private String c50;
    private String c51;
    private String c52;
    private String c53;
    private String c54;
    private String c55;
    private String c56;
    private String c57;
    private String c58;
    private String c59;
    private String c60;
    private String c61;
    private String c62;
    private String c63;
    private String c64;
    private String c65;
    private String c66;
    private String c67;
    private String c68;
    private String c69;
    private String c70;
    private String c71;
    private String c72;
    private String c73;
    private String c74;
    private String c75;
    private String c76;
    private String c77;
    private String c78;
    private String c79;
    private String c80;
    private String c81;
    private String c82;
    private String c83;
    private String c84;
    private String c85;
    private String c86;
    private String c87;
    private String c88;
    private String c89;
    private String c90;
    private String c91;
    private String c92;
    private String c93;
    private String c94;
    private String c95;
    private String c96;
    private String c97;
    private String c98;
    private String c99;
    private String c100;

}
