server:
  address: 0.0.0.0
  port: 8091
  servlet:
    context-path:
    session:
      cookie:
        name: TEST_JSESSIONID
      timeout: 3600
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain,application/javascript
  error:
    whitelabel:
      enabled: false
    include-exception: false
    include-stacktrace: never
    path: /error

---

spring:
  config:
    activate:
      on-profile: local
  application:
    name: SPRING-BOOT-NATIVE-TEST
  webservices:
    path: /home
  banner:
    charset: UTF-8
  main:
    banner-mode: console
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB
  messages:
    encoding: UTF-8
  mvc:
    converters:
      preferred-json-mapper: jackson
  output:
    ansi:
      enabled: always
  autoconfigure:
    exclude:
      -org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      -org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration